var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                            x",
   "x                                                                            x",
   "x@                          x                                                x",
   "xxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxwwwxxxxxxxxxxxxxxxxxx   xxxxxx",
   "x                xxxxx                                                       x",
   "x                                                                            x",
   "x                                                                            x",                                                                              
   "xxxxx   xxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxwxxxxxxxxxxxxx",
   "x                        xxxxx     x  x  x                     xxx           x",
   "x                                                                            x",
   "x                x  w                          w   x                         x",
   "xxwxxxxxxxwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxx",
   "x                                   xx                                       x",
   "x                                                                            x",
   "x                           xx                                               x",
   "xxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxxxwxxxxxxx   xxxx",
   "x  xxxxxxx                             x    xxx               xxx            x",
   "x                                                                            x",
   "x                                                                            x",
   "xxxxx   xxxxxxwxxxxxxxxxwwwxxxxxxxxxxxxx   xxxxxxxxxxxxwxwxxxxxxx!xxwwxxxxxxxx",
   "x                                      x   x          xxxxx      !           x",
   "x                                      x   x                     !           x",
   "x                                      x   x                     !           x",
   "xxxxxxxxxxwxxxxxxxxxxxxxxxxxxxx   xxxxxx!!!xxx    xxxxxxxxxxxxwwwxxxxxxxxxxxxx",
   "x                                      xxxxx     xx  !       xxxxx           x",
   "x                                                    !                       x",
   "x                                                    !!!!!!!!!         xx    x",
   "xxxx   xxxxxxx!xxxxxx|xxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx    x",
   "x            xxx    xxx   x!!x                                     x    x    x",
   "x                         xxxx                                    x     x o  x",
   "x                                                                x      xggggx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxwxwxwxxwxxxwwwwxxxxxxxxxxxxxxxxxxxggggx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                            x",
   "x                                                                            x",
   "x@                                                                           x",
   "xxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxx|xxxxxxxxxxxxx|xxxxxx|xxxxxx|xxxxxxxxxxxxxxxx",
   "x                 xxx           xxx           xxx    xxx                     x",
   "x                                                                            x",
   "x                                                                            x",                                                                              
   "xxxxx   xxxxxxxxxxxxxxxxxx!!!xxx|xxxxx|xxxx|xxxxxxx|xxxxxxxxxxxxwxxxxxxxxxxxxx",
   "x                        xxxxx xxx   xxx  xxx     xxx     x                  x",
   "x                                                         x                  x",
   "x                x  x                          x   x                         x",
   "xxwxxxxxxxxxxxxxxx| xxxxxxxxxxxxxxx|xxxxxxxxxxxxx|xxxwxxwxxx   xxxxxxxxxxxxxxx",
   "x                xx|xx            xxx                 x                      x",
   "x                 xx                                  x                      x",
   "x                           xx                        x                      x",
   "xxxx!!!!!xx   xxxxxxxxx|xxxxxxxxxxxxxxxxxxxxx|xxxxxxxxxxxxxxxxxwxxxxxxx   xxxx",
   "x  xxxxxxx            xxx             xx    xxx               xxx            x",
   "x                                                                            x",
   "x                                                                            x",
   "xxxxxxwwwwxxxxxx xxx|xxxxxxx|xxxxxxxxxxx   xxxxxxxxxxxxwxwxxxxxxx|xxwwxxxxxxxx",
   "x              x|x xxx     xxx         x   x          xxxxx     xxx          x",
   "x              xxx                     x   x                                 x",
   "x                                      x   x                                 x",
   "xxxxxxxxxxwxxxxxxxxxxxxxxxxxxxxxxxxxxxxx| |xxx    xxxxxwxxxwxxwwwxxxxxxxxx  xx",
   "x                                      xx xx     xx  !       xxxxx           x",
   "x                                               xx   !                       x",
   "x                                              xx    !!!!!!!!!         xx    x",
   "xxxx   xxxxxxx!xxxxxx|xxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx    x",
   "x            xxx    xxx   x!!x                                     x    x    x",
   "x                         xxxx                                    x     x o  x",
   "x                                                                x      xggggx",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxwxwxwxxwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                            x",
   "x                                                                            x",
   "x@                                                                           x",
   "xxxxxxxxxxxxxxxxxxxwwwwwxxxxxxxxxxxxxwwwxxxxxxxwwwwwwxxxxxxwwwxxxxxxx   xxxxxx",
   "x                                                                            x",
   "x                                                                            x",
   "x                                                                            x",                                                                              
   "xxxxx   xxxxxxxxxxxxxxxxxxwwwxxxwxxxxxwxwxxwxxwwxwwwwwwwwxxxxxxxwxxxxxwwwxxxxx",
   "x                                      x|xx|xx||xx|xx|xx|xx                  x",
   "x                                                         x                  x",
   "x                                                         x                  x",
   "xxwxxxxxxxxxxxxxxw| wxxxxxxxxxxxxxxwxxxx|xx|xx||xw|xxww|xxxxxxxxxxxxxxxxxxxxxx",
   "x                xx|xx                 x              x                      x",
   "x                 xx                   x              x                      x",
   "x                           xx         x              x                      x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!xxxxxxxxxwxxxxxxx   xxxx",
   "x                                     xxxxxxxxxxxxxxxxx       xxx            x",
   "x                                                                            x",
   "x                                                                            x",
   "xxxxxxwwww   xxwwwxxwxxxxxxxwxxxxxxxxxxxw|wxxxxxxxx|xxxwxwxxxxxxx|xxwwxxxxxxxx",
   "x                                       xxx       xxx xxxxx     xxxxx        x",
   "x                                                                   x        x",
   "x                                                                   x        x",
   "xxxxxxxxxxwxxxxxxxxxxxxxxxxxxxxxxxwwwwwwwwwxxx    xxxxxwxxxwxxwwwxxxxxxxxx  xx",
   "x                                                    !       xxxxx           x",
   "x                                                    !                       x",
   "x                                                    !!!!!!!!!         xx    x",
   "xxxx   xxxxxxx!xxxxxx|xxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxx    x",
   "x            xxx    xxx   x!!x                                     x    x    x",
   "x                         xxxx                                    x     x o  x",
   "x                                                                x      xggggx",
   "xxxxxxxxwwwxxxxxwwwxxxxxxwwwxxxxxxxxxxxwxwxwxxwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
